spring.application.name=File_Sharing

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=DropZone



server.servlet.context-path=/api
spring.data.mongodb.auto-index-creation=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#
#clerk.issuer=https://gentle-dane-39.clerk.accounts.dev
#clerk.jwks-url=https://gentle-dane-39.clerk.accounts.dev/.well-known/jwks.json