spring.application.name=File_Sharing

spring.data.mongodb.uri=mongodb://localhost:27017/DropZone



server.servlet.context-path=/api
spring.data.mongodb.auto-index-creation=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#
#clerk.issuer=https://gentle-dane-39.clerk.accounts.dev
#clerk.jwks-url=https://gentle-dane-39.clerk.accounts.dev/.well-known/jwks.json